site_name: c13n Documentation
site_favicon: 'https://c13n.io/c13n-avatar.png'

theme:
  name: readthedocs
  navigation-depth: 4
  custom_dir: theme_overrides
  logo: 'https://c13n.io/c13n-avatar.png'

extra_css:
- stylesheets/style.css

nav:
  - Home: index.md
  - Payload Protocols: protocol.md
  - API documentation: /projects/api